version: "3"

services:
  app:
    container_name: tg2vk-server
    build: .
    ports:
     - "8080:8080"
    networks:
      - tg2vk-net
    links:
     - db
    environment:
     - TG2VK_DB_URL=postgresql://db:5432/tg2vk_local
  db:
    container_name: tg2vk-postgres
    image: "postgres:latest"
    environment:
     - POSTGRES_USER=tg2vk_local
     - POSTGRES_PASSWORD=tg2vk_local
     - POSTGRES_DB=tg2vk_local
    expose:
     - "5432"
    networks:
      - tg2vk-net

networks:
  tg2vk-net:
    driver: bridge