version: "3"

services:
  db:
    container_name: tg2vk-server-db
    image: "postgres:latest"
    environment:
     - POSTGRES_USER=tg2vk_local
     - POSTGRES_PASSWORD=tg2vk_local
     - POSTGRES_DB=tg2vk_local
    ports:
     - "5432:5432"
    networks:
      - tg2vk-net
  app:
    container_name: tg2vk-server-app
    build: .
    ports:
     - "8080:8080"
    networks:
      - tg2vk-net
    links:
     - db
    environment:
     - TG2VK_DB_URL=postgresql://db:5432/tg2vk_local

networks:
  tg2vk-net:
    driver: bridge
